name: yolo_streamlit_showcase

services:
  yolo_streamlit:
    build: .
    ports:
      - 34000:8000
    volumes:
      - ./src:/app/src
      - ./.streamlit:/app/.streamlit
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8000
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_THEME_PRIMARY_COLOR=#2e7d32
    restart: unless-stopped
