# Service stack name
name: yolo_streamlit_showcase

services:
  # YOLO object detection with Streamlit UI (CPU version)
  yolo_streamlit:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - BASE=cpu
        - PYTORCH_CUDA=cpu
    ports:
      # Map container port 8000 to host port 34000
      - 34000:8000
    volumes:
      # Map source code and configuration for hot reloading
      - ../src:/app/src
      # Map logs directory to persist logs
      - ../logs:/app/logs
    environment:
      # Core application settings
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      # Streamlit server configuration
      - STREAMLIT_SERVER_PORT=8000
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_THEME_PRIMARY_COLOR=#2e7d32
      # Logging configuration
      - LOG_LEVEL=INFO
      - LOG_TO_FILE=true
      - LOG_FILENAME=/app/logs/app.log
    # Restart policy
    restart: unless-stopped
    # Container labels
    labels:
      app.description: "YOLO object detection showcase with Streamlit UI"
      app.maintainer: "CDS Team"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/_stcore/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s

  # YOLO object detection with Streamlit UI (GPU version)
  yolo_streamlit_gpu:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - BASE=gpu
        - PYTORCH_CUDA=cu118  # For CUDA 11.8
    ports:
      # Map container port 8000 to host port 34001 (different from CPU version)
      - 34001:8000
    volumes:
      # Map source code and configuration for hot reloading
      - ../src:/app/src
      # Map logs directory to persist logs
      - ../logs:/app/logs
    environment:
      # Core application settings
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      # Streamlit server configuration
      - STREAMLIT_SERVER_PORT=8000
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_THEME_PRIMARY_COLOR=#2e7d32
      # Logging configuration
      - LOG_LEVEL=INFO
      - LOG_TO_FILE=true
      - LOG_FILENAME=/app/logs/app_gpu.log
    # Use NVIDIA runtime
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # Restart policy
    restart: unless-stopped
    # Container labels
    labels:
      app.description: "YOLO object detection showcase with Streamlit UI (GPU)"
      app.maintainer: "CDS Team"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/_stcore/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s 