[theme]
base="light"
primaryColor = "#01b387"
textColor = "#333333"
font = "monospace"

[server]
port = 8000
address = "0.0.0.0"
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8000 